api:
  insecure: true
  dashboard: true
accessLog: {}
providers:
  docker:
    network: quizzify-online-tests_proxy
entryPoints:
  http:
    address: ":80"
  grpc:
    address: ":8000"

log:
  level: DEBUG